version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - postgres_db
    volume:
      - ./test:./build/reports/tests/test/*
  postgres_db:
    image: "postgres:13.1"
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: db1
      POSTGRES_PASSWORD: password1
      POSTGRES_USER: root