version: "3.7"
services:
  api_service:
    restart: always
    ports:
      - 8083:8080
    command: gradle test -i
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:13.1"
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: db1
      POSTGRES_PASSWORD: password1
      POSTGRES_USER: root